name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          HOST: 13.124.3.73
          USERNAME: ubuntu
          KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          # 프라이빗 키를 파일로 저장
          echo "${KEY}" > key.pem
          chmod 400 key.pem

          # SSH 연결 및 애플리케이션 배포
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            cd /var/www/html &&
            git pull origin master ||
            git init &&
            git remote add origin <GitHub-Repository-URL> &&
            git pull origin master &&
            cd frontend &&
            npm install &&
            npm run build &&
            cd ../backend &&
            npm install &&
            pm2 restart backend-app || pm2 start app.js --name 'backend-app'
          "
