name: Deploy Static Frontend to EC2

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build # 정적 파일 빌드 (next build 사용)

      # 4. Create .ssh directory
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # 5. Add known_hosts
      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 6. Deploy to EC2
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
          PRODUCTION_ENV_VARS: ${{ secrets.PRODUCTION_ENV_VARS }}
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem

          # Build 결과물을 EC2 서버로 복사
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" frontend/out/ $USERNAME@$HOST:/var/www/html/frontend/

          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            # 디렉토리 확인 및 환경변수 작성
            if [ ! -d /var/www/html/frontend ]; then
              mkdir -p /var/www/html/frontend
            fi

            # 환경변수 작성
            echo '${PRODUCTION_ENV_VARS}' > /var/www/html/frontend/.env.production

            # Nginx 재시작
            sudo systemctl restart nginx
            echo '.env.production created with the following content:'
            cat /var/www/html/frontend/.env.production
          "
          rm key.pem
