name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh

      - name: Add known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
          ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem
          rsync -avz --exclude 'node_modules' -e "ssh -o StrictHostKeyChecking=no -i key.pem" backend/ $USERNAME@$HOST:/home/ubuntu/backend/
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            # Install Node.js and PM2 if not installed
            if ! command -v npm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash &&
              . ~/.nvm/nvm.sh &&
              nvm install 18 &&
              npm install -g pm2
            fi

            cd /home/ubuntu/backend &&
            echo '${ENV_FILE_CONTENTS}' > .env &&
            npm install &&
            pm2 restart backend || pm2 start ecosystem.config.js --env production;
          "
          rm key.pem
