name: Deploy to EC2

on:
  push:
    branches:
      - master # master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          HOST: 13.124.3.73 # EC2 퍼블릭 IP
          USERNAME: ubuntu # EC2 사용자 이름
          KEY: ${{ secrets.EC2_PRIVATE_KEY }} # GitHub Secrets에 등록된 프라이빗 키
        run: |
          # 프라이빗 키를 파일로 저장
          echo "${KEY}" > key.pem
          chmod 400 key.pem

          # SSH 연결 및 애플리케이션 배포
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            # nvm 환경 활성화
            export NVM_DIR=\$HOME/.nvm &&
            [ -s \$NVM_DIR/nvm.sh ] && \. \$NVM_DIR/nvm.sh &&
            nvm use 22.13.0 &&

            # 프로젝트 배포
            cd /var/www/html &&
            if [ ! -d .git ]; then
              git init &&
              git remote add origin git@github.com:username/repository.git
            fi &&
            git pull origin master &&

            # 프론트엔드 설치 및 빌드
            cd frontend &&
            npm install &&
            npm run build &&

            # 백엔드 설치 및 실행
            cd ../backend &&
            npm install &&
            pm2 restart backend-app || pm2 start app.js --name 'backend-app'
          "
