name: Deploy Next.js Frontend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Next.js app
        env:
          CI: false
        run: |
          cd frontend
          npm run build

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
          # Install NVM, Node.js, and PM2 if not installed
          if ! command -v npm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash &&
              export NVM_DIR=\$HOME/.nvm &&
              [ -s \$NVM_DIR/nvm.sh ] && \. \$NVM_DIR/nvm.sh &&
              nvm install 18 &&
              npm install -g pm2
          fi

          # Deploy frontend
          mkdir -p /home/ubuntu/frontend/.next &&
          rsync -avz -e \"ssh -o StrictHostKeyChecking=no -i key.pem\" frontend/.next/ $USERNAME@$HOST:/home/ubuntu/frontend/.next/ &&
          cd /home/ubuntu/frontend &&
          npm install &&
          pm2 restart frontend-app || pm2 start npm --name 'frontend-app' -- start --prefix /home/ubuntu/frontend;
          "
          rm key.pem
