name: Deploy Next.js Frontend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Next.js app
        env:
          CI: false
        run: |
          cd frontend
          npm run build

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem
          # Ensure remote directory exists
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "mkdir -p /home/ubuntu/frontend/.next"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" frontend/.next/ $USERNAME@$HOST:/home/ubuntu/frontend/.next/
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            cd /home/ubuntu/frontend &&
            npm install &&
            pm2 restart frontend || pm2 start npm --name 'frontend-app' -- start;
          "
          rm key.pem
