name: Deploy Frontend to EC2

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh

      - name: Add known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Frontend to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
          FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" frontend/ $USERNAME@$HOST:/home/ubuntu/frontend/
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            if ! command -v npm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash &&
              export NVM_DIR=\$HOME/.nvm &&
              [ -s \$NVM_DIR/nvm.sh ] && \. \$NVM_DIR/nvm.sh &&
              nvm install 18 &&
              npm install -g pm2
            fi
            cd /home/ubuntu/frontend &&
            echo '${FRONTEND_ENV}' > .env &&
            pm2 restart frontend-app || pm2 start npm --name frontend-app -- start --prefix /home/ubuntu/frontend;
          "
          rm key.pem
