name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Deploy Backend
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
          ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}
        run: |
          echo "${KEY}" > key.pem
          chmod 400 key.pem
          rsync -avz --exclude 'node_modules' -e "ssh -o StrictHostKeyChecking=no -i key.pem" backend/ $USERNAME@$HOST:/home/ubuntu/backend/
          ssh -o StrictHostKeyChecking=no -i key.pem $USERNAME@$HOST "
            cd /home/ubuntu/backend &&
            echo '${ENV_FILE_CONTENTS}' > .env &&
            npm install &&
            pm2 restart backend || pm2 start ecosystem.config.js --env production;
          "
          rm key.pem
